### ISSUE TITLE
HistoryScreen activity changes its state after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [mpcjanssen/simpletask-android#1001]
When I change the orientation of the device screen, HistoryScreen activity changes its state. Below there are different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- first case --
The menu situated on the right-bottom of the activity disappears
![2019-07-25 01-14-18_before](https://user-images.githubusercontent.com/53469180/62222332-767e0900-b3b3-11e9-9f31-e27240ceb4ae.png)
![2019-07-25 01-14-18_after](https://user-images.githubusercontent.com/53469180/62222334-767e0900-b3b3-11e9-8ae8-f2479b16aa7d.png)

-- second case --
The main text partially disappears
![2019-07-24 14-17-05_before](https://user-images.githubusercontent.com/53469180/62222337-77169f80-b3b3-11e9-94d9-cb53c7469a3e.png)
![2019-07-24 14-17-05_after](https://user-images.githubusercontent.com/53469180/62222339-77169f80-b3b3-11e9-97ac-c937a4ce3aca.png)

**Comment by mpcjanssen** [comment]
The main text doesn't really dissappear, it is showing the first item from the history again. This could be fixed. All menu popup issues are probably unfixable.

**Comment by mpcjanssen** [comment]
Seems issues created by some automated process spamming hundreds of projects with the same minor issues. Wont fix unless there is anything where dataloss is occurring.

**Comment by smichel17** [comment]
In my opinion, this functionality -- at least in its basic form -- ought to be provided by the Android SDK.

Currently, when the device is rotated, Android recreates dialogs and some other elements from scratch. In order to have them reflect previous state, developers need to hand-code that persistence. That is, any time the contents of a dialog change in response to user input, you have to save the new state and serialize it into a bundle. Then, when the dialog is created, you have to check whether there was a previous state and initialize accordingly.

This is not that big of a deal if you are already using a heavily customized dialog. However, if you're using a stock dialog or a very lightly customized one (eg, stock widget in base dialog), it's a fair amount of extra work. Sometimes it's a lot of extra work, if your data is difficult or complicated to serialize. And, of course, it's another place you run the risk of introducing new bugs.

Especially in cases where there is not very much impact on users, it's very hard to justify spending time in.

For your research: I'm a contributor to Simpletask and the primary maintainer of Red Moon, which also experienced this issue (a time picker that does not maintain its state across device rotation).
