### ISSUE TITLE
Save filters in data folder

### ISSUE THREAD

**Issue by Dominik-K** [mpcjanssen/simpletask-android#101]
The filters should be saved also in the data folder where todo.txt and done.txt are stored. That way I can also backup my created filters.
The reason: I deinstalled Simpletask (with F-Droid; for installing an older version) and now see that all my filters are gone.

The filters could be also an enhancement for the todo.txt community ... (-:

**Comment by paullemmens** [comment]
Any update on this?

**Comment by mpcjanssen** [comment]
Didn't have a chance to implement this yet. I am still considering it though. I am just not sure how to combine this with the Google M backup feature.

**Comment by paullemmens** [comment]
Not entirely sure what the M backup is, but from a quick google it appears
to be some sort of newer/better device backup/sync solution for Android M.

From that angle I would love you to consider both options, because I
presume that many simpletask users cannot or do not want to (immediately)
upgrade to M to be able to sync these filter settings. So the "backup" of
doing it from within the app to me seems a worthwhile investment.

**Comment by mpcjanssen** [comment]
Agreed, but I would prefer to handle both cases with the same framework. That said an export/import of the filters is almost trivial (it's an xml file).

**Comment by smichel17** [comment]
@mpcjanssen How often do you reinstall the app or change devices? I'd wager it's few enough times that most people are happy to do the manual work of selecting where to export to / import from, as long as they _can_ import/export.

I suggest adding manual import/export to file only, and closing this issue. Then create a someday/maybe issue for the M backup stuff, which seems like it isn't particularly actionable at the moment.

**Comment by mpcjanssen** [comment]
Import Export should be easy. I will move this up in prio.
