### ISSUE TITLE
Creating duplicate of selected task(s)

### ISSUE THREAD

**Issue by tveulemans** [mpcjanssen/simpletask-android#1034]
Hi,

Is there a way (via a Lua script) to create copies of the selected task(s)?

Alternatively, could this be added as a feature?

Kind regards,
Thomas

**Comment by mpcjanssen** [comment]
select a task and sharing it with simpletask will create a copy. it's not a very direct way though. Can you explain the usecase?

**Comment by tveulemans** [comment]
Regarding the use case: I have a few high-level tasks (e.g., following an online course) that I want to break down in smaller steps (e.g., a specific lesson) while retaining most of the characteristics of the 'parent' task. 

I will give the workaround a try - thanks!

**Comment by smichel17** [comment]
I thought it used to be that if you are filtered on certain lists and tags, when you add a new task it will be pre-filled with those. Doesn't seem to be the case any more though. Maybe changed when we removed the pre-fill checkbox in favor of two separate buttons (enter and (+))?

**Comment by aubreyz** [comment]
I'm not following here. Isn't it easy enough to use the clipboard to copy the task text and paste it into a new one (once or multiple times)?

At least my end new tasks do pre-fill with the filtered @ and +

**Comment by mpcjanssen** [comment]
@smichel17 still works for me, but only with the plus button. Getting it the work triggered by the keyboard enter was a PITA and had unintended side effects.

**Comment by mpcjanssen** [comment]
@tveulemans as @smichel17 indicated, It might work well if you use a tag for the big task to treat is as a project and then add next tasks using the plus button in the UI.

**Comment by tveulemans** [comment]
@mpcjanssen OK thanks for the suggestion, I'll give it a try and will close the issue.

**Comment by smichel17** [comment]
@mpcjanssen We're on the same page about how things work on the AddTask activity. That won't work, though, since we're talking about adding more tasks after the fact, and when editing, addTask checks that you have the same number of tasks you started editing with.

I meant adding a new task from the FAB in the main activity. I tried again just now, and it turns out it does still pre-fill, but only under certain circumstances. Didn't spend more time figuring out what those are because it'll be easier just to look at the code when I get back to my computer.

**Comment by mpcjanssen** [comment]
@smichel17 I removed the checking of addTask of the same number of tasks as I find it very unintuitive. Prefill from FAB works if at most one context and/or one tag is selected.
