### ISSUE TITLE
Android 11 storage problems

### ISSUE THREAD

**Issue by Rudd-O** [mpcjanssen/simpletask-android#1100]
Hello.  Latest version of the app.

App starts and says "cannot load todo.txt" (enoent in the log).  I create some tasks, they are created fine.  File todo.txt is saved in /storage/emulated/0/Android/data/nl.mpcjanssen.simpletask/files/todo.txt.  All good.

Problem arises when I want to open another todo.txt (I use syncthing to keep the list in sync with my PC) in another directory.  No matter which folder I look into, or place the todo.txt file in, the file browser just can't see it, and it's always permission denied in the log.  But the file browser shows me jpg and mp3 files?!  (Actually that is consistent with how Android describes these days the storage permission that your app uses).

So I decide I am going to put my folder with todo.txt and config.lua somewhere under /storage/emulated/0/DCIM, and then rename todo.txt to todo.jpg.  Et voila, now the app can actually load and save the todo.jpg file, because obviously it's a text file but the app doesn't care (and neither does my desktop app).  Folder sync also works, everythingis fine.

Except I cannot load config.lua — the OS says permission denied.  I now have an app that is about 10% as functional as it was in Android 10, because the lua scripts I have did a TON of heavy lifting for me.

How can this be fixed?

Thanks.

**Comment by mpcjanssen** [comment]
I don't know how this can be fixed with the new permission model for storage in Android 11. If someone knows how I would be very interested, but I am tired of the arms race with Google on storage access

**Comment by Rudd-O** [comment]
I think if you use the standard Storage Framework file chooser, and let the user choose a folder, then it grants you access *just* to that folder, even if it is outside of `~/Android/data`.  Your app uses a homecooked file chooser.

**Comment by Rudd-O** [comment]
Yes https://developer.android.com/about/versions/11/privacy/storage#file-access

**Comment by smichel17** [comment]
Looks like you can request access to all files https://developer.android.com/about/versions/11/privacy/storage#all-files-access

I wonder whether this would be approved by app store review. But it should work on fdroid at least.

...but yes, it seems like every new version or two, Android introduces some new hoop top jump through if you want storage access. Tbh they should just cut it off entirely, which would at least make clear their intent, instead of constantly asking devs to play keep-up to maintain existing functionality.

**Comment by mpcjanssen** [comment]
@Rudd-O using the storage file framework is not really an option because simpletask uses file monitoring events to check for changes in other apps and saf doesn't support this. This would break a very common user case

**Comment by mpcjanssen** [comment]
I did make a SAF version and that also had issues with properly synching files opened using saf on remote providers.

**Comment by mpcjanssen** [comment]
@smichel17 I doubt simpletask matches the required criteria to request that level of access

**Comment by Rudd-O** [comment]
Can you poll every second instead of monitor?  Not suggesting this is the way, perhaps all files access is enough.  The thing is, I would gladly let the app use its normal data directory as it does, but then I can't actually put the config.lua file there, AND syncthing can't sync from that folder either.

This is bullshit man, damn android.

**Comment by smichel17** [comment]
I wonder if it would make sense to use the all-files permission for cloudless and just not distribute that version on the play store

> syncthing

I wonder if the "right" way to do this, according to Google, would be to make a syncthing flavor, as another storage backend like Nextcloud/dropbox. :roll_eyes:

…this is why I am becoming increasingly skeptical of sandboxing a la Android/iOS/flatpak/snap, etc. Instead of a shared abstraction (the filesystem) that makes apps interoperable by default, integrations must be added individually by developers. In the name of allowing people to control what apps can do on their device, it limits what people themselves can do. I do appreciate it when I am forced to run apps I do not trust, but I would much rather if I never had to run apps like that.

**Comment by mpcjanssen** [comment]
It seems that android O (API level 26) adds an option to refresh a cached file in the SAF cache, This would allow a version based on SAF. I will make a proof of concept at https://github.com/mpcjanssen/simpletask-android/tree/saf

**Comment by mpcjanssen** [comment]
Even while being a POS PITA, the SAF version does seem to work now. Getting a reliable lastModified result is unreasonably hard.

**Comment by mpcjanssen** [comment]
Adding file manage permissions is a very small change and works perfectly on Android R. I will make a Android R build and add the link.

**Comment by mpcjanssen** [comment]
Android R version with full access at https://mpcjanssen.nl/artifacts/10.9.0-2-f162a66-fullaccess/cloudless/

**Comment by Rudd-O** [comment]
Will this be released?  Thanks in advance.

**Comment by Rudd-O** [comment]
FYI I can confirm this works perfectly.

**Comment by mpcjanssen** [comment]
@Rudd-O I can't really release this because Simpletask will probably not meet the Google requirements for this permission. Also this build only works on Android 11. I will keep putting updated builds on my site though.

**Comment by smichel17** [comment]
Until this is resolved in a way that users can figure out how to make ST work on Android 11 without coming here, I suspect there will be a steady stream of new issues from people who forget to search or didn't find this issue when they searched. Pinning this to hopefully avoid some of that.

**Comment by mpcjanssen** [comment]
Funny that the Android 11 storage issue is issue nr #1100 :)

**Comment by dessalines** [comment]
For anyone wondering, the earliest version of simple-task available on f-droid still works (10.5 I think?).

**Comment by Rudd-O** [comment]
Yes.  It's probably because it targets an older version of Android?  (But what do I know, to be honest — all I know is Android apps are getting more and more walled-in, certainly for good reason, but the way the chessboard was set up from the start was going to lead us here.)

**Comment by Rudd-O** [comment]
> I will keep putting updated builds on my site though.

Can this be the default in F-Droid?  I can confirm your build works **perfectly**, for all readers of this issue.

**Comment by mpcjanssen** [comment]
@Rudd-O unfortunately not as is because the functionality to get this permission is only available on api 30. I could do some rewriting to change the behavior based on api level.

**Comment by Yur7y** [comment]
> 
> 
> For anyone wondering, the earliest version of simple-task available on f-droid still works (10.5 I think?).

For anyone looking for a functional version: Here is the link on @mpcjanssen's site to the 10.5 version, since it is no longer available on F-Droid: https://mpcjanssen.nl/artifacts/10.5.4-7-3c06437/cloudless/release/

**Comment by qazip** [comment]
I am trying to install the 11 version on mi a2 lite (android 10) but I get "problem parsing package".

Even though I am not on android 11, I still can't access my todo file. I have given storage access, but all I get while browsing storage looking for the file is "..."

**Comment by mpcjanssen** [comment]
You can't use the 11 version if you are not on android 11 because it uses a new permission. Can you try https://mpcjanssen.nl/artifacts/issues/1088/app-cloudless-release.apk?

**Comment by paulgirard** [comment]
I confirm that version works on Android 11 and syncthing.
Just for information it seems that by default the file access authorization proposed by default is "media file" and not "all kind of files". I couldn't pick a todo.txt from my syncthing because of this. I had to check permissions in Android SimpleTask app page and select "all kind of files" (not the exact phrase) instead of "only media files".
Hope that comment will help others like a future me :)

Thank you very much @mpcjanssen for your work :pray:
