### ISSUE TITLE
default todo.txt location?

### ISSUE THREAD

**Issue by rafaqz** [mpcjanssen/simpletask-android#255]
Is there a simple way to change the default todo.txt location so I don't have to keep going to "Open todo file?"

**Comment by mpcjanssen** [comment]
What do you mean exactly here? Once you change your todo file, Simpletask will re-use this todo file when you reopen it (even after a reboot). If this is not happening for you, that's a bug.

If you mean the default when reinstalling, then there is no easy way to store settings for an app which will survive a deinstallation. This is by design, Google is working on a way to save application settings in the cloud, but I haven't looked into that yet.

**Comment by rafaqz** [comment]
Ok after restarting it is working. Initially when I pressed the back button
simpletask would go back out of my todo.txt to the default file, and I
would have to reopen. Maybe there is a little bug in there somewhere.

**Comment by mpcjanssen** [comment]
I have never seen this behavior, but I will check if there is something which could cause this.

**Comment by mpcjanssen** [comment]
Ah I think I know what is causing this. If you press back, simpletask will
go back to the previous todo file. I never use back to exit from the app. I
press the home button. I could make the file trail configurable I guess.

**Comment by dbadolato** [comment]
I am having a related problem with this functionality for the back button:
I usually use back to exit from the apps in my phone (Samsung S2). When I forgot that it does not work anymore that way in SimpleTask, then the app "loads" some sort of previous and/or default todo.txt file (.../Dropbox/todo/todo.txt)... that does not exist in my Dropbox account (and as far as I remember never existed). I then get an error message (which, by the way, has a small spelling error with "Drobox" instead of "Dropbox"). I then have to manually select again my proper todo.txt file.
Nothing critical, just a bit anoying.

**Comment by mpcjanssen** [comment]
Yes this is the history functionality. I personally dont like it that much either so I will revert it and add recent files in another way.

**Comment by mpcjanssen** [comment]
With removal of history functionality this is as fixed as it can be.
