### ISSUE TITLE
Selection menu doesn't show

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#291]
If I open the app by selecting an item in the widget, not always, but in many cases, the menu (for editing, prioritizing, etc..) does not come up. Then I need to unselect and select the item again to have that menu. It is not something crucial, but it would be nice to have it fixed.

**Comment by jotwewe** [comment]
For me this is a major bug because of two related things:
 - the selected item is not visible, usually one has to scroll a lot to find it
 - in contrast to previous versions the menu (which sometimes does not come up) does not show the number of selected items

These issues make opening simpletask by touching the widget a source of errors.

**Comment by mpcjanssen** [comment]
Scrolling to a specific position is a remarkably difficult thing to achieve. But I will look into this again if I have some time.

**Comment by mpcjanssen** [comment]
See also #307 for a possibly related bug.

**Comment by mpcjanssen** [comment]
Should be fixed with new way of tracking selection.
