### ISSUE TITLE
Share setting option no longer available

### ISSUE THREAD

**Issue by fmartelg** [mpcjanssen/simpletask-android#292]
The settings menu used to have an option to edit tasks being shared from other apps before adding them to to-do.txt 

This option appears to be missing. I am no longer able to edit shared tasks.

**Comment by mpcjanssen** [comment]
The way background adding of tasks worked could cause data loss. Instead now when adding tasks in the background you can append a configurable text. That way it is easy to review the tasks in Simpletask later. (for example configure `+bg` and filter for the `bg` tag)

I hesitate to re-add the setting because as mentioned it is difficult to make it work in all scenarios. One option might be to add the tasks first and then open the editing screen. This should work, but for me the option above works much better. For example opening the edit screen when adding tasks using Google Note 2 Self by voice.

**Comment by fmartelg** [comment]
@mpcjanssen Thanks.  How do you set that?  I go to Settings > Behaviour > Background tag and add `+background`.  Then I go to Chrome and share a web page with Simpletask.  The url gets added as a task but no tag.  I rebooted phone.  Same behavior.  

Note that even if this works, it is a long and tortuous road.  I would need to share > filter > edit > unfilter back to my default filter.

Obviously I don't want to loose my data but I hope this is not the long term solution.  Surely there has to be a better way.

**Comment by mpcjanssen** [comment]
I noticed that the tag is only applied if you use google now note to self. This is a bug and I will fix that. I will also see if it is possible to open the task editor after the tasks have been added to the todo file to prevent the data loss scenario.
