### ISSUE TITLE
Cursor on beginning of line after setting or changing priority

### ISSUE THREAD

**Issue by erysavy** [mpcjanssen/simpletask-android#329]
Simpletask v6.0.9:
Create a new task, choose priority from widget. After this the cursor is positioned *left* of the widget, hence when adding e.g. the context(s) (`@xxx`) and/or project (`+yyy`) this will lead to something like:
`@context some descriptive text (A)`

The same happens to the cursor when changing the priority for an existing task.

Preferred behavior: the cursor shouldn't be touched. When inserting anything at or before the cursor position, it should move with the inserted text, otherwise remain where it was before.
The task priority is handled differently as it should always be place at the beginning of the line, but this shouldn't change the cursor's behavior.

**Comment by fmartelg** [comment]
Yes.  Very annoying.

**Comment by mpcjanssen** [comment]
Trying to keep the cursor at the same spot is a tricky problem. For example what if you remove the tag where the cursor currently is or what if you add a priority so that where the cursor currently is moves.
I did have a sort of working solution before, but that had a tendency to crash because setting the cursor past the end of the textfield is not allowed.
I will look into restoring this behavior as I agree it's annoying. I just want to add it safely.

Random rambling, the structural text support of the EditText is non-existent, you can't even get a specific line.

**Comment by erysavy** [comment]
As I haven't seen your previous solution, what I suggest might be too simple, but nevertheless.
Assuming you can get the whole line content and are able to get and set the cursor position, the following rules should be sufficient:
1. when deleting anything beginning left of the current cursor position, calculate the new position as:
max((old cursor position - length of deleted text), start position of deleted text)
2. inserting text beginning up to the current cursor position: new position = old position + length of inserted text (differing from 1. this includes e.g. the case where the cursor is at n, insert at n)
3. Replacing text is the same as deleting and then inserting the replacement (if you're replacing directly, only calculate the cursor position this way)
4. should never apply, but to be sure: limit new cursor position to the interval [0, length of line]
5. set the cursor position to the calculated value

Replacing text under the cursor (the case you mentioned) would lead to a new cursor position where the original text started in step 1, shifting it to the right when inserting the replacement, which I as a user would expect.
E.g. with the Cursor at "%":
```(B) @conte%xt some descriptive text```
replacing "@context" to something else leads to:
```(B) @othercontext% some descriptive text```
Don't forget to take into padding spaces that are added or deleted.

I hope this is of any use for you :)

**Comment by mpcjanssen** [comment]
@erysavy I have used a slightly simpler approach

* When changing the prio, move the cursor position to match for the new or removed prio.
* When changing due or threshold date don't change the cursor position

This should work for most cases. I also made sure that I am not setting the cursor out of bounds now which should eliminate the crashes.

As such this is will be fixed in 6.3.3
