### ISSUE TITLE
Bug: Setting 'Date new tasks' affects tasks edited

### ISSUE THREAD

**Issue by bttrx** [mpcjanssen/simpletask-android#337]
If 'Date **new** tasks' is enabled and I edit some **existing** task with no creation date so far, then the current date is written to the task as creation date.

**Comment by mpcjanssen** [comment]
I can reproduce this and I agree it's a bit weird. 

The main problem to fix this is that it's not very clear what is a new task and what is an updated task. Mainly because the you can add tasks while updating other tasks. It also doesn't help that tasks don't really have an identity (it's just strings) apart from maybe the line number in the `todo.txt`.

I'll have to think very hard on how (if possible) to fix this.

**Comment by bttrx** [comment]
Does updating a task change its position in todo.txt?

**Comment by mpcjanssen** [comment]
It shouldn't

**Comment by bttrx** [comment]
Then the line number is your unique identifier. ;-) Or what about hashing a line?

**Comment by mpcjanssen** [comment]
Hashing wont work if you change the task: For example if you have two task: `A` and `A later` and you change the first to `A later` and the second to `A even later` it wont work with hashes,

However when you update tasks and new ones Simpletask already replaces the update tasks based on the position in the Edit box. Currently the code is not in place to take creation date into account when this happens but I am working on a DB backend which should make it possible to fix this.

This will take some time to implement though as it has a major impact on the code.
