### ISSUE TITLE
Cursor placed at beginning of line after adding a list

### ISSUE THREAD

**Issue by cjbcjb** [mpcjanssen/simpletask-android#365]
Previously, when I added a list to a new empty task, the cursor would be placed after it, and I could continue typing the task entry. Now, it is placed before the list that I chose, and I must move the cursor after it before beginning to type. Just to test things, I added a list to an existing task, and it moved the cursor to the beginning of the task. Is this a bug or is it new intentional behavior?

**Comment by cjbcjb** [comment]
After spending some time with it, I now think I like it better this way. Having the list tags at the end of the task makes them easier to read. So, never mind unless you did not intend for it to work this way.

**Comment by mpcjanssen** [comment]
This was a slightly unintended side effect of fixing bugs with updating the lists (removing and adding). Turns out that it's very difficult to restore the cursor position when changing the tags or lists. Nothing really works for all scenarios so I have given up trying (trying also lead to frequent out of bounds exceptions)
