### ISSUE TITLE
[Feature Request] Calendar time blocks

### ISSUE THREAD

**Issue by Erulisse** [mpcjanssen/simpletask-android#370]
If the user could specify specific start and stop times in tasks this would be splendid. It seems like you could easily acquire this by using thresholds as the start time to an appointment and due: as the end time. The idea does require some tweaking because currently thresholds make a task invisible until t:DATE.

**Comment by mpcjanssen** [comment]
Threshold date doesn't necessarily hide a task (it's a setting in the filter Other tab)

I don't want to add a start time and en time as there is no real well established way to do that in todo.txt. I am a bit hesitant to make Simpletask a full calendar application. Not because I can't see the use, but because it's complicated to get right and it will need to be supported.

I will leave this request open though, because I might change my mind :smile:

**Comment by vojtechkral** [comment]
This is in a similar vein to #210.

Long story short, this is tricky to do right. Once a bunch of dates _and times_ are added to tasks, they become very verbose and hard to read and the syntax becomes complex or requires a whole bunch of extensions, making it hard to stay plain-text friendly and it also requires a lot of user interface. So far I wasn't able to figure out a decent way to accomplish this without making the application horribly complicated.

Anyway, the calendar features were meant as a way to bring simple reminders funcionality to Simpletask without reinventing the wheel. Maybe I should've named it "Reminders" instead, because that's pretty much only thing it does, it creates reminders for you so that you don't have to.

It definitely doesn't manage calendar(s).

**Comment by mpcjanssen** [comment]
Time blocks in calendar will probably not be merged. It's a lot of maintenance and development work and it makes the text part of todo.txt too complicated. If you want tasks at specific times use the existing add reminder option, or add it to the calendar directly. Simpletask is not intended to be a calendar replacement.
