### ISSUE TITLE
Feature Request: Toggl Integration

### ISSUE THREAD

**Issue by JonathanReeve** [mpcjanssen/simpletask-android#381]
It'd be really cool to get Toggl Integration, such that when you select a task, you'd have the option of starting a task timer for it. Tags and projects could be automatically passed along to Toggl. I'm already doing this in vim, with toggl.vim and todo.txt.vim, but it'd be great to get this for Android, too.

**Comment by mpcjanssen** [comment]
A toggl integration will require integration with an API over internet. Simpletask Cloudless doesn't have internet permissions. Because it is mostly used by people who can't use apps with internet permissions because of security restrictions, this is never going to change.
I do not want to make this integration in the dropbox version only because that would make the two code bases too different.
So I will not consider this (or any similar) integrations, sorry.
