### ISSUE TITLE
Change simple touch-click on a task

### ISSUE THREAD

**Issue by ddisanti** [mpcjanssen/simpletask-android#382]
It would be nice to exchange behavior between long and single "click" on task list. Most of the time you have to edit a task and I think it is more natural go to edit task screen after a single "click" instead of showing contextual menu.

**Comment by smichel17** [comment]
I don't think 'exchnage' is the word you're looking for -- as far as I can tell, there is no difference in behavior between a press and a tap. Both show the contextual menu. I think you're proposing changing the default behavior on tap to 'edit' instead of 'select'.

I feel like this change would help some people (you and me) but hurt others (those with checkboxes disabled). Perhaps a better solution would be to add a preference, "default tap action" where you can define what happens on tap? I would avoid adding preferences when possible -- what about long press to edit?

**Comment by mpcjanssen** [comment]
@ddisanti, @smichel17 is correct that this change would hurt others (me for example). So this will only change with an additional setting. However the settings list is already huge so I am a bit hesitant to add even more.
How are you editing a task which cannot be done by selecting it and making modifications from the menu then?

**Comment by smichel17** [comment]
@mpcjanssen If I want to change the wording of a task, I'll tap to select and then hit the edit button. @ddisanti's proposal would remove the intermediary 'tap to select' step.

For me personally, it is not that big of a deal / I would not have created a ticket for this, in large part because all of the solutions I see cause bigger issues than the problem it's trying to solve.

**Comment by smichel17** [comment]
Here's a more specific scenario: I have an @waiting list as per GTD for things I'm waiting on. It's in the format: `t:when-to-check-in-with-this-person @waiting [what I'm waiting on] -> [what I'll do when that thing is done] @context-of-the-thing-i'll-do`. When the person I'm waiting on does the thing I'm waiting for, instead of completing the task, I'll modify it and delete everything up through the `->`, and now I've got the task I want, already entered.

**Comment by mpcjanssen** [comment]
Also note that single click also pops up screen to dial numbers or go to URLs now. Making single click edit will also collide with this. So concluding save one click and make everything else more complex, is not going to happen.

**Comment by smichel17** [comment]
Agreed. Two-click to edit is not a big hardship and not worth the added complexity.
