### ISSUE TITLE
Change the position of the new Floating Action Button.

### ISSUE THREAD

**Issue by ddisanti** [mpcjanssen/simpletask-android#397]
It overlays the "Salto de línea automático" ("Word wrap") when Spanish is the system language. On Spanish most of the times all phrases gets longer.
![screenshots_2016-03-20-11-18-35](https://cloud.githubusercontent.com/assets/17773786/13904951/577bb38e-eeba-11e5-81b3-c9620dcc00a3.png)

**Comment by mpcjanssen** [comment]
I don't know where I could put it then. I should probably move the settings in a drawer.

**Comment by smichel17** [comment]
You could definitely shorten the `@`, `+`, `due`, and `t` menus, making room for an overflow menu in the corner, like you have when you select todo items from the main screen.

**Comment by mpcjanssen** [comment]
@smichel17 I don't understand what you mean exactly here. In the main screen if you select an item the FAB disappears. How will this work in the AddTask screen?

**Comment by mpcjanssen** [comment]
Proposal:

![screenshot_2016-03-20-16-58-59](https://cloud.githubusercontent.com/assets/146895/13905335/597da342-eebd-11e5-8f39-22e55209dc4c.png)

![screenshot_2016-03-20-16-59-04](https://cloud.githubusercontent.com/assets/146895/13905340/65da8f24-eebd-11e5-9622-6186e4f7cea9.png)

**Comment by ddisanti** [comment]
Sorry about the noob question, but it would be wrong move it a little
higher so it will show over the menus?

**Comment by mpcjanssen** [comment]
you mean the side drawer?

**Comment by smichel17** [comment]
I believe @ddisanti is asking if we could move the FAB up so it's fully in the text box.

I'd avoid the drawer solution, because there's no visual indicator that the drawer exists, and people simply won't find these (useful) options.

I see two acceptable solutions:

1. Move those two options into the drop down menu
2. Create a new overflow menu in the bottom row.

![move_fab](https://cloud.githubusercontent.com/assets/6563664/13905514/2b8cf458-ee98-11e5-8786-304c5d94c358.png)

**Comment by ddisanti** [comment]
I speak Spanish. Sorry if I'm not clear about what I'm trying to express.
I meant move up the New Button so it will be over the @.., +.., etc. menus.

**Comment by ddisanti** [comment]
@smichel17 , your proposal looks nice, since these options are not changed
too often, and in case you need them, it would take just one more tap.

**Comment by smichel17** [comment]
For reference, here's a mockup with what @ddisanti proposed:

![higher_fab](https://cloud.githubusercontent.com/assets/6563664/13905553/43171ae4-ee99-11e5-8945-a47dba8c6198.png)

**Comment by mpcjanssen** [comment]
Ah I understand now. BTW @smichel17 why do you use the Send icon to add/update the tasks? Is this in the material guidelines somewhere?

**Comment by ddisanti** [comment]
@smichel17 , you've got it. ☺

**Comment by smichel17** [comment]
@mpcjanssen haha, it's because I'm doing this all in pixel art with GIMP; the FAB I'm using, I just grabbed from a screenshot of a different app (so I don't need to worry about resizing it for the mockup, which is based on a screenshot of Simpletask on my phone).

It's not in the material guidelines that I can remember (though I haven't read them end-to-end), but a high percentage of other todo apps (at least, those on f-droid) use them for saving tasks.

**Comment by mpcjanssen** [comment]
So this will be it:

![screenshot_2016-03-20-18-03-06](https://cloud.githubusercontent.com/assets/146895/13905641/17ee18d6-eec6-11e5-802c-35c45a036878.png)

**Comment by mpcjanssen** [comment]
@ddisanti @smichel17 

How about this to make the addition buttons more obvious??
![screenshot_2016-03-20-18-23-19](https://cloud.githubusercontent.com/assets/146895/13905752/12bd6332-eec9-11e5-9910-9c224245107a.png)
![screenshot_2016-03-20-18-23-52](https://cloud.githubusercontent.com/assets/146895/13905753/12c04c5a-eec9-11e5-9e67-5851d8a16199.png)

**Comment by smichel17** [comment]
@mpcjanssen I like it.

FWIW, I also liked it better when `Word wrap` was centered instead of left aligned.

**Comment by ddisanti** [comment]
@mpcjanssen , it looks good. Thanks.
