### ISSUE TITLE
Sticky reminders for the day

### ISSUE THREAD

**Issue by aurisnoctis** [mpcjanssen/simpletask-android#432]
Hey Simpletask team,

I have the calendar reminder feature enabled and it works great so far: the reminders all appear on time.

However, they all disappear at once whenever I open Simpletask for the first time (for instance to work on one of these tasks or to do something completely unrelated to the reminders).

Is there a way to make reminders stick around until they are actively dismissed from the notification area by the user?

Thanks in advance!

**Comment by vojtechkral** [comment]
Hi.

This is problematic. I presume the reason those notifications disappear is that Simpletask will re-create all the calendar events/notifications each time todo list is updated. The code managing the calendar events doesn't really have a way to tell which events need updating, deleting, etc., so it just removes them all an re-creates from scratch.

I guess I'd have to somehow diff the current state against the calendar data. I'm not entirely sure it's possible.

**Comment by vojtechkral** [comment]
I'll have a look in a couple days, hand tight.

**Comment by ddisanti** [comment]
@vojtechkral @aurisnoctis ,  that's true. Every time the list is updated, the Calendar app shows nothing. It's empty. It's that so for a few minutes until it regenerates all its data. A bad side effect is the battery drain. If you do edit tasks too often with calendar reminders activated,  once you've done take a look at the battery level and go check the battery statistics. Calendar provider will be on top of it. Because of that, I deactivate Calendar Reminders and use the "Set reminder" option instead.

**Comment by aurisnoctis** [comment]
@vojtechkral Thanks!

Didn't check for battery drain, but for me the reminders for today don't get regenerated. They just disappear for good whenever Simpletask is launched.

**Comment by smichel17** [comment]
I imagine it will be difficult not to regenerate calendar reminders until the backend identifies tasks by line number instead of my text.

**Comment by vojtechkral** [comment]
@smichel17 Well, I can diff the task between the list and the calendar by text & date. The sync is also delayed to a thread so that it doesn't occur too often - I could also increase this delay. Right now it's just 1sec, which is probably too short.

**Comment by aurisnoctis** [comment]
@vojtechkral Update: At the moment I don't receive calendar reminders anymore. I have updated Simpletask since my first entry in this issue, but I don't know if it could be related to that. My usual  calendar reminder configuration is: 0 days in advance at 08:00 for due dates. For testing purposes, I made a test task due tomorrow, and changed the config to 1 day in advance at <2 minutes from now> for due dates. The notification does not appear.

**Comment by vojtechkral** [comment]
@aurisnoctis Ok, thanks for the report. I am reworking the way events/reminders are created, so this'll probably change...

**Comment by smichel17** [comment]
@vojtechkral replying from #440.

Ok. The delay on task change is definitely a good thing, and also I think a user would expect that the calendars be created/deleted immediately when the feature is enabled/disabled in settings. Would that be a reasonable amount of work to implement?

**Comment by vojtechkral** [comment]
@smichel17 It probably wouldn't be hard to implement, but I'm not sure I see the point. The delay is currently 1 second, I was planning to increase to about 15 seconds. I don't think the change can be immediately visible anyway as it takes a couple of seconds to switch from Simpletask to the Calendar app. Calendar apps also tend to have delayed refreshing.

**Comment by mpcjanssen** [comment]
Line numbers are not a good measure for task identity, neither is the text itself. One of the disadvantages of a plain text format is that tasks don't really have an identity at all.

A possible approach could be to add event handlers for adding removing and updating tasks with a before and after so the appropriate calendar item can be add, updated or removed.

**Comment by vojtechkral** [comment]
@mpcjanssen I'm working on a diffing solution - generate events, read calendar, compare, update. I just haven't finished it yet...

**Comment by smichel17** [comment]
I'll just throw it out there that I've always found it odd that automatic calendar reminders are generated at a certain time of day.
- If I need to set a task for a specific time of day I'm going to create a reminder from it
- If I just need it done any time that day, I'd rather make it an all-day event.
  - All-day events would mean we can remove the "time of day" setting, too :+1:

**Comment by mpcjanssen** [comment]
The disadvantage of all day events is the alarm occurs somewhere around midnight. All day events with customisable alarm time don't exist. So for me the setting makes sense.

**Comment by smichel17** [comment]
@mpcjanssen Can you explain what you're looking to get out of this feature / how you use it & your calendar? My explanation is:

Tasks that need to get done at a certain time, I put on my calendar for that time. Tasks that need to get done on a specific *date,* I do not want a reminder for (because that would imply they're due at that time). The reason I'd want them on my calendar at all is so my calendar can become my definitive source of all things that I *must* get done today. If I need to review stuff on my lists or calendar at a certain time, that's a separate thing I'd add an appointment or set an alarm for (in actuality, I don't do either, it's just the first thing I do when I wake up).

**Comment by aurisnoctis** [comment]
Hey all,

I started using the calendar reminder feature so I don't even have to remember to open SimpleTask for due tasks on a given day.

I choose calendar reminders "0 days in advance" so they automatically appear as notifications on that day (at the time I specify).

I'd like the notifications to stay until I manually dismiss them.

The time at which the notifications appear has a user-friendly function, too: I prefer to review tasks before the day schedule starts, so I pick something like 7:00. If a user prefers not to be disturbed in the morning, something like 15:00 is suitable to still have a chance to get the things done on that day.

That's just my use case, and it may not be what the original idea was. Have a nice weekend, all!

**Comment by smichel17** [comment]
@aurisnoctis Thank you, that was very useful.
You still need to open Simpletask to check off those tasks at some point, right? If Simpletask put reminders in the status bar itself, and when you dismissed them it automatically completed that task, would that be a more convenient workflow for you?

@mpcjanssen @vojtechkral I'm not saying we should do this particular solution; it's meant to illustrate that we have options, here.
Of course this is entirely selfish: calendar reminders are really useful, but the current implementation doesn't fit with my workflow. Maybe there's a solution that would make it useful to me, without making it less useful for you. I need to know your use cases before I can try to find that solution, though.

**Comment by aurisnoctis** [comment]
@smichel17 I don't mind manually dismissing the calendar reminder before or after diving into SimpleTask.

The completing of a task by manually dismissing the reminder is probably not desirable as dismissing the reminder is rather a "don't remind me now/today" (delaying it to a later time) than a "done".

I am looking forward to how this develops! The one thing that would make me happy is if calendar reminders didn't disappear just by opening SimpleTask. Sometimes there are too many reminders to remember. If the reminders all disappear at once, what is left is a fuzzy "some tasks are due!" reminder instead of the specific list. In the end it just depends what (you all that think) brings most benefit to users.

**Comment by smichel17** [comment]
@aurisnoctis It was a direction to go in, not a completely worked out idea :P
To flesh it out a little more (though still not complete): I swiping the notification away would likely only dismiss the notification; there'd be an action in the notification's dropdown to complete the task and maybe also one to change the due and/or threshold date.

**Comment by vojtechkral** [comment]
@smichel17 
> The reason I'd want them on my calendar at all is so my calendar can become my definitive source of all things that I must get done today.

Hmm, I don't see how calendar helps you with these, surely you could have simpletask show you the tasks that are due today, couldn't you?

> If Simpletask put reminders in the status bar itself, and when you dismissed them it automatically completed that task, would that be a more convenient workflow for you?

As far as I recall this is @mpcjanssen said this was out of Simpletask's scope (and I can see why), sorry.

My usecase is as follows: Ocasinally I get tasks that are due at a specific date & time a further away in the future. For example, a doctor's appointment on a monday, 8am, in _5 months_. That's a very specific date&time that is way to far in the future for me to remember. I might also easily overlook the task in Simpletask. Therefore, I like to set a reminder that reminds me some 2-4 days beforehand so that I don't forget about the appointment during those 5 months. Of couse, a decent calendar app would take care of that for me, but using most Android calendar apps is as convenient as scratching your left ear with your right foot (a saying in my native language).

I _might_ be able to do without the reminder if I used threshold date + the _hide tasks in with threshold in future_ feature. Haven't looked into that yet...

@aurisnoctis 
> I'd like the notifications to stay until I manually dismiss them.

I am working on it, I was away this weekend, I hope to get some work done during this week...

**Comment by smichel17** [comment]
>Hmm, I don't see how calendar helps you with these, surely you could have simpletask show you the tasks that are due today, couldn't you?

I can and do, but I wish I didn't have to. I'd like them on my calendar because I follow GTD's recommendation of using the calendar only for truly time-sensitive stuff (as opposed to "I want to get this done today but I could technically postpone it"). Then Simpletask is for things with no concrete due date. The corollary is that I'd like *all* time-sensitive things to end up on my calendar, so it's a single point of truth for my time-sensitive commitments and I don't *also* have to review simpletask.

>As far as I recall this is @mpcjanssen said this was out of Simpletask's scope (and I can see why), sorry.

 No worries, it was just an example. Also, it would not meet my needs, because there would still be time-sensitive todo's that are not on my calendar, so I think there is probably a better solution that meets both @aurisnoctis' needs and mine :)

>I might be able to do without the reminder if I used threshold date + the hide tasks in with threshold in future feature. Haven't looked into that yet...

This is what I do. I have an INBOX filter that shows all tasks ~~with no context~~ not on a list. I review my calendar and that every morning. So when I want a reminder of something in the future, I set its threshold date to the time I want the reminder, and I see it that morning.

However, as I said, I try to keep time-sensitive things on my calendar and not simpletask, so in your example, I would likely use Android's built-in reminder functionality to add a reminder 24 hours, 2 days, or 1 week in advance.

>a decent calendar app

I've been pretty happy with [etar](https://f-droid.org/repository/browse/?fdfilter=etar&fdid=ws.xsoh.etar). It makes dealing with Android calendars merely painful (instead of 'downright impossible').

You can use [activity launcher](https://f-droid.org/repository/browse/?fdfilter=activity+launcher&fdid=de.szalkowski.activitylauncher) to create a shortcut directly to adding a calendar appointment. Then I use my [AcDisplay fork](https://github.com/smichel17/AcDisplay) that replaces the 'dialer' and 'camera' corner swipe actions with intents to open the simpletask AddTask activity / create a new calendar appointment.

Then if you're rooted with xposed, you can use the [app settings](https://github.com/rovo89/XposedAppSettings) app to allow etar/simpletask to run over the lockscreen, so you don't need to unlock your phone to do those actions (though this does allow others to look at your todo lists and calendar without unlocking your phone).

**Comment by vojtechkral** [comment]
I'm using Etar too... It's not bad but... The calendar app on my old Nokia dumbphone was still more effective :)

**Comment by smichel17** [comment]
I'm not sure if this changed, but my simpletask reminders are now showing up as all day events that also have a non-midnight reminder time (-17 hours before the event, haha). This is nearly perfect! The only additional thing I'd like is the option not to set a reminder at all.

Also, found out that the AddTask activity can run over the lock screen by default so no need for xposed for that (the same is not true of etar and I couldn't figure out the right place to add it).

**Comment by vojtechkral** [comment]
Hi. Recent integration of calendar diffing update should alleviate the problem of calendar reminders being re-created even if they are unchanged.

Also, for a nicer calendar reminder management, I'd highly recommend the excellent quarck/CalendarNotification app that makes notifications persist and allows snoozing.

**Comment by vojtechkral** [comment]
Closing for now, please report back if there's further problems.
