### ISSUE TITLE
I tried any.do . It is so visually inspiring.

### ISSUE THREAD

**Issue by getthemike** [mpcjanssen/simpletask-android#433]
I know it's not fair to compare. They have a subscription model and a large team but wow. The app is beautiful. 

I suggest anyone interested in amazing ui for a task management app should go look at it. 

The todo.txt compatibility is a different premise than just making a beautiful app but if you can steal any design notes from them you would be doing simpletask a huge favor. 

I love the changes I am seeing but looking at their ui was a great experience.

tagging suggestion: this was meant as a design reference or inspiration

**Comment by smichel17** [comment]
So, there's two different kinds of design at play here: appearance and functionality. Visual designers are experts in appearance and interaction designers are experts in functionality. (People often confuse interaction design with user experience design because UX is a buzz word right now; UX includes both functionality _and_ appearance.)

I am an interaction designer (in training), but have little expertise in visual design (though I'd like to learn more, and of course I have opinions like everyone else). #411 is intended to address functionality; any changes to the visuals are side effects only.<sup>[1](#footnote)</sup>

I looked at the screenshots on the Play store and agree that it has really good visual design. It's hard to figure out anything with the functionality side of things without installing the app, and it requires more permissions than I am comfortable allowing on my personal phone. I'll see if I can get it to work on an emulator.

---

###### <a name="footnote">1</a>: This isn't _quite_ true, because there is some overlap between visual and interaction design, like -- if an interface is cluttered, it isn't as pretty (visual), and it can be hard to find the button you're looking for (interaction).

**Comment by mpcjanssen** [comment]
I suck at visuals, that said I am not willing to sacrifice ease of use for slickness and the current design maps my personal ease of use. Of course I am very open to suggestions. Also nice visuals are a lot of work and require time I rather spend on functionality.

**Comment by smichel17** [comment]
>I suck at visuals [...they] are a lot of work and require time I rather spend on functionality [...] I am not willing to sacrifice ease of use for slickness

Noted; I will try to keep new visuals to a minimum. Also it doesn't make sense to spend time on visual work until functionality is totally nailed down, at least with a team this size :stuck_out_tongue_winking_eye:

**Comment by smichel17** [comment]
I played with Any.do. Its model is simpler than ours: There are lists. Lists have items. Items have a title, attached notes or media, and subtasks, which only have a title.

-You can set three types of reminders: one-time, recurring, or location-based.
- You can also share/delegate items with other people who have Any.do accounts, which allows them to mark the item as complete.
  - Significant downside: your list is stored on their servers
-You can view all lists or a single list at a time.
-You can sort by date, list, or priority.

If I had to do GTD with it, I'd make a list for each area of responsibility, an item for each project, and then a bunch of next actions as subtasks. I'd set a location-based notification to simulate context. Since I can only set that for an item, not a subtask, I'd set it for that project's next action, then set it again when I completed that next action. In short, Any.do isn't designed for GTD, so many of the design decisions -- while mostly good -- aren't applicable to simpletask.

I also have doubts about how well it would function for managing a list the size of mine, which typically hovers between 90 and 120 items. Which is fine, it just means I'm not in Any.do's target audience.

That said, Any.do is still a todo app, so there are places (filtering, editing tasks) where I can and will draw inspiration; they absolutely nail the visual design aspect; and they have some useful features like a rundown of unscheduled and due tasks (shows you the tasks one at a time and guides you through either scheduling or postponing them).

Also some details that really nail the 'feel' criteria, like their long press to edit or rearrange.

**Comment by mpcjanssen** [comment]
There are already a couple of UI redesign issue. Will close this one as a duplicate see #484 and others for latest updates.

**Comment by Vijayanth-Reddy-K** [comment]
I had started with Any.do, but moved to Simpletask for a few reasons. The small size and the ability to access and backup the to-do files, to name a few. But the main reason was that my phone somehow stops all app notifications if they are not from Google, so having Google Calendar integration via Simpletask finally allowed me to get notifications and reminders.

That said, the layout of Any.do is nice, and while exploring lua scripting with Simpletask, I discovered that it is possible to atleast organise the items in the main screen as Any.do does, using lua. The organisation I am speaking of is as shown in the picture [here](https://lh3.googleusercontent.com/JMYtdwZv6zXI0-wtBMo3scpt5jYPEJVKBSqPkCz9Ie_FPYDf7vaHwQ-A9LpdNOOwheq6=h900).

Three things need to be done. First, you need to change the sort order. If you are not filtering out completed tasks, the first two entries in the sort order must be `V Completed` followed by `V By Due Date`. Otherwise, make the first entry `V By Due Date`. Next, you need to add the following to the global Lua config file:

```lua
function group_by_due_date(t, f, e)
    --[[Group tasks by due date. Output ranges are: 'Already Overdue!!!', 'Due Today', 
        'Due in the rest of this Week' (next 6 days after today), 'Due in the remainder of this Month' (next 3 weeks after this week), 
        and 'Can Afford to Procrastinate on these for now!' (sometime after the next 30 days, or no due date set)]]

    local curr_time, day, week, month = os.time(), 86400, 518400, 2505600   -- See above for details.

    if f.due ~= nil then
        if curr_time-day >= f.due and f.completed == false then
            return "Already Overdue!!!"

        elseif curr_time >= f.due and curr_time-day < f.due and f.completed == false then
            return "Due Today"

        elseif curr_time < f.due and curr_time+week >= f.due and f.completed == false then
            return "Due in the rest of this Week"

        elseif curr_time+week < f.due and curr_time+month >= f.due and f.completed == false then
            return "Due in the remainder of this Month"

        elseif f.completed == false then
            return "Can Afford to Procrastinate on these for now!"

    else
        return "Completed Tasks"
        end

    elseif f.completed == false then
        return "Can Afford to Procrastinate on these for now!"

    else
        return "Completed Tasks"

    end
end
```

Then, use this in the main application or widget as a script:

```lua
function onGroup(t, f, e)
    return group_by_due_date(t, f, e)
end
```

Note 1: The addition of _group_by_due_date_ to the lua confuguration file is only so that if multiple widgets use this grouping, you do not have to copy the complete code to each widget. You can replace `function group_by_due_date(t, f, e)` with `function onGroup(t, f, e)` and use the whole function directly in a script too.

Note 2: When compared to Any.do, where you have to make do with the categories provided by the app, with this function, you can group your tasks under headings you choose and under the time duration you want, by changing the constants defined for day, week, etc.
