### ISSUE TITLE
Use the same icons in the main view and edit view

### ISSUE THREAD

**Issue by djibux** [mpcjanssen/simpletask-android#443]
Hello,

Most of the time I add tags, lists or priorities from the main screen.
Some of the time I do it from the edit screen.

I wonder why the icons in those two screens are different: it always confuses me.  It would seem much more coherent to me to just stick with one representation, for instance "priority" should always be either :star: or `(.)`.  Either one is OK, but I find having both confusing.

**Comment by smichel17** [comment]
They're different because the main screen adds priority, lists, tags, etc to all tasks selected, where the edit screen only does so to the task that the cursor is on.

This may be an insufficient reason to change them, but you should also read #128 and related discussions since they are relevant here.

**Comment by djibux** [comment]
I see.  I don't edit multiple tasks from the edit screen that much.

Well, the shift functionality would work for me I guess…

**Comment by mpcjanssen** [comment]
@djibux I think making the icons consistent makes sense. I am not sure why I made it different in the first place. Probably because the add task screen shows the actual plain text.

**Comment by tomfbush** [comment]
I hope this is in the right debate about icon consistency... But I forget which of the icons that look like tags and paper to add projects and contexts is which. I would think just having icons of + and @ would not only make the approach cater for nuanced uses of those parts of the syntax but also make it easier for me to remember ;-) in my head a tag icon relates far more to a context

Tom

**Comment by mpcjanssen** [comment]
@tomfbush I didn't consider usages where `@` and `+` mean different things (for example the todo.txt context and project). I will see how it looks if I use the textual representation instead of the icons.

**Comment by smichel17** [comment]
- The icons are aesthetically pleasing and more clearly interactive.
- The icon for threshold in #481 gives a better impression of the intended use for threshold dates than text.
- `@`, and `+` more clearly describe their function than their icon counterparts
- The icons for priority and due date (in #481) are roughly equivalent to their text counterparts. 
- The edit icon is absolutely superior to text, but it belongs on a FAB anyway so that doesn't matter.

I think the best compromise is to use all icons (ie, the current setup), but to switch to using `@` and `+` based on the `use todo.txt terms` setting.

**Comment by mpcjanssen** [comment]
@smichel17 that is a good idea, but I would prefer not to change the UI too much based on settings, it's a lot of work to maintain. 
I will use the icons everywhere so it's consistent and maybe update the list icon to a more intuitive one (I am open for suggestions)

**Comment by djibux** [comment]
@mpcjanssen, the tag icon has a + in the bottom right corner.  Maybe you could adapt the list icon to have a @ in the bottom right corner.

**Comment by smichel17** [comment]
There's some smaller UI changes to the selection screen that we're made recently. They include new icons, and selection options moved out of the menu at the bottom, making these interfaces closer to mirroring one another in function.

Updated my comment above to reflect my latest thinking.

I wonder if it is possible to remove the words "list" and "tag" everywhere (just use `@` and `+`) and then remove the todo.txt terms setting. 

For more about editing, start with #128 and then there are a bunch of linked issues from there.
