### ISSUE TITLE
Investigate taskwarrior backend

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#457]
Taskwarrior has several advantages:
- It has a proper sync implementation based on a server that can be hosted on your own device
- As a result it has proper task identity
- It's completely open (JSON data store and opensource)

It would resolve the main issue I have with todo.txt which is conflict resolution and reliable sync.

**Comment by smichel17** [comment]
If you did this, I hope there would still be a way to support using a todo.txt file. todo.txt is one of the major draws of the app for me (and actually the reason I found it in the first place -- I was looking for todo.txt apps).

**Comment by mpcjanssen** [comment]
This is intended to become a storage backend. Todo.txt is not going anywhere.

**Comment by mpcjanssen** [comment]
The thing I dislike about todo.txt as a backend ia that you dont have a task identity. So syncing doesnt work very well.

**Comment by ddisanti** [comment]
I've tried Taskwarrior a few months ago. Although it looks promising, it wasn't mature enough and the fact that configuring a server added extra complexity that I dislike. In terms of functionality, SimpleTask is just great. I think it just needs more work on UI to go from great to awesome.

**Comment by smichel17** [comment]
@ddisanti if I understand correctly, switching backends is an issue on the dev side of things: no task identity means some features are more work to implement than they should be.

re: UI, not sure if you've seen #411. I don't agree with all my thoughts at the time (which is why that issue is closed, pending new thoughts and sketches).

**Comment by ddisanti** [comment]
@smichel17 I've seen #411. It looked very promising. Until it was close I was eager to see it implemented.

**Comment by mpcjanssen** [comment]
The rationale behind all this is that brilliant as todo.txt is, it has two major drawbacks.

1. It's a single text file which is very easy to destroy.
1. It doesn't have a task identity which make syncing and merging hard.

I am investigating different storage backends to remedy both issues.

**Comment by mpcjanssen** [comment]
Btw i reopened #411 be to keep the mashups in my attention

**Comment by smichel17** [comment]
I split it into two issues since one of them (#411) is actionable right now and I am re-thinking the other (#458).

**Comment by colinsullivan** [comment]
I hadn't heard of taskwarrior before.  Interesting!

FWIW:

I've been using BitTorrent Sync on my android & OS X machines.  It generally works very well.  The downsides for me:

* Although BitTorrent's NAT traversal tech is quite robust, sometimes it takes a bit of trouble for my phone and laptop to find each other.  Because of this, I am in the habit of checking to make sure they are synced when I switch from being at my workstation to going mobile.  Sometimes I fail, then I have to fix merge conflicts manually.  It works much better when I have a world-accessible node running (such as a home server with ports open to the world).
* BitTorrent Sync drains my HTC One (a few years old) battery, probably like 30% faster than without.

**Comment by mpcjanssen** [comment]
Taskwarrior is too complex to set-up (especially the server `taskd` part). I will not continue with this,

**Comment by mpcjanssen** [comment]
After being bitten by some accidentally lost tasks because I forgot to save a todo.txt file again and after having set-up a taskd server again, I do want to look back into this again.

**Comment by vojtechkral** [comment]
Task identity does sound good...

**Comment by mpcjanssen** [comment]
Groundwork for this is now in the taskwarrior branch.

**Comment by mpcjanssen** [comment]
Taskwarrior has a completely different way of handling filtering and sorting. As a result it cannot easily be integrated into Simpletask. I have another repo where I made a working TW version which reuses the TW filters and sort. [1](https://github.com/mpcjanssen/simpletask-taskwarrior)

**Comment by kai11** [comment]
@mpcjanssen Any update on this? Are you going to proceed? TW repository is 10 months old.

**Comment by mpcjanssen** [comment]
@kai11 the reason the TW repository is so old is that it works very well. It could use some polish. However it is so different from the todo.txt way of doing things that integrating it with simpletask-android will not work well. So integration will not happen. The separate taskwarrior version will is still something I would like to continue.

**Comment by gour** [comment]
> The separate taskwarrior version will is still something I would like to continue.

Do you still consider that?

I really like taskwarrior, but due to the missing features in regarding 'recurrence overhaul' which is supposed to happen in 2.6/3.0, I had to migrate to org-mode, although I feel i'm more productive with tw.

However, both tw/org-mode have problem with the lack of decent mobile client - that's why I consider to deploy todo.txt along with simpletask-android for certain category tasks.

In order to sync with the desktop I'm considering nextcloud version. Is it safe to bet on it since atm I'm syncing my calendars/contacts with Baikal server and would have to migrate to nextCloud?

**Comment by mpcjanssen** [comment]
@gour 
Note that the nextcloud version syncs to a todo.txt file on nextcloud, not to nextcloud tasks.
I sort of left the current taskwarrior version at the moment because actually modifying tasks is completly different from how todo.txt does it.
Synching does work much better with taskwarrior, so I haven't abandoned it yet.

**Comment by gour** [comment]
> Note that the nextcloud version syncs to a todo.txt file on nextcloud, not to nextcloud tasks.

OK, that's fine since I anyway never used tasks with nextcloud.

> I sort of left the current taskwarrior version at the moment because actually modifying tasks is completly different from how todo.txt does it.

You mean there is already some prototype of simpletask-taskwarrior available?

> Synching does work much better with taskwarrior, so I haven't abandoned it yet.

In any case, having simpletask working with taskwarrior would be terrific!

**Comment by smichel17** [comment]
https://github.com/mpcjanssen/simpletask-android/tree/taskwarrior
