### ISSUE TITLE
UX Update: Filtering

### ISSUE THREAD

**Issue by smichel17** [mpcjanssen/simpletask-android#484]
> **Design goal:** Require fewer taps and less context change to access common info and functions

Right now all configuration is hidden behind the 'edit filter' button. For example, grouping/sorting and other display options. It's rather painful to have to enter a different view to perform a core action of the app (changing grouping/sorting). There are workarounds (create filters with different views), but that's not an excuse to avoid fixing the problem. This issue exists to figure out exactly how all that should work.

> **Design goal:** Be more material.

Guidelines should be broken IFF there's a good reason, but trying to fight the system results in a harder-to-maintain and buggier application.

Material design guidelines prohibit drawers on the right. That's because drawers are hidden functionality that the user is unlikely to discover for themselves (I used simpletask for a few weeks before I realized the drawer existed).

Filters are first class citizens in Simpletask. They are the core that makes this app so convenient to use. They should not be relegated to a nonstandard location.

---

Iteration 1 tries to move all features from the filter view into the main view. I think that makes the main view too cluttered.

For iteration 2, I posit that changing which _tasks_ show up in each of your saved filters is not a common activity. Therefore, we can move those controls ~~into the settings~~ off the main screen, freeing up a lot of space in the UI. Mockups forthcoming.

**Comment by smichel17** [comment]
Placeholder

**Comment by smichel17** [comment]
Placeholder

**Comment by smichel17** [comment]
First iteration

> ### a. Remove the filter drawer
> 
> ### b. Move filter settings
> 
> **Tasks tab:**
> 
> When you scroll down on this tab, the tab bar hides itself. Scrolling up or swiping sideways shows it again.
> 
> ![home-tasks](https://cloud.githubusercontent.com/assets/6563664/14406206/3d8dd0b4-fe6f-11e5-8211-f6dc92e20089.png)
> 
> **Any other tab:**
> 
> ![home-prio](https://cloud.githubusercontent.com/assets/6563664/14406337/d6ac03f8-fe72-11e5-9114-0400d0815b7b.png)
> 
> ### c. Clean up
> 
> We save updates to filters through the main view now, so we don't need it in the filter view. That means the filter selection overflow menu has only one item left in it (rename), and we can just use an icon for that.
> 
> ![filter-select-one-final](https://cloud.githubusercontent.com/assets/6563664/14406398/495203ac-fe74-11e5-838a-33d7437eb201.png)
> 
> When you create a new widget, it will simply open up the app's main screen, with two differences.
> - [ ] **The "save" button in the app bar will be removed
> - [ ] The FAB on the Tasks tab will also be replaced with a "check" FAB
> 
> These changes will make #417-type widget creation more confusing. This should be addressed when tackling #417, not here.

**Comment by smichel17** [comment]
Conversation copied from the other thread:

> > > > *@alphalpha007 said:*
> > >>
> > > >Honestly adding separate tabs for lists and tags is just adding the number of clicks required. On the same note, I'd like to say that what makes simpletask great is that the app goes onto the background because of its intuitiveness. The user and his tasks get priority over how the app looks. If material design would come in the way of that, please avoid implementing it. Just a humble request from a user who uses the app to get his work life in order.
> > >
> > > *@smichel17 said:*
> > >
> > > I am also unhappy with the iteration above. That's okay; it's just an iteration. I need to block out a chunk of time to continue iterating and really think this through, I just haven't gotten there yet.
> > > 
> > > For the record, I also agree that while all things equal I'd like to follow the material design guidelines, they are also just that: guudelines. So they're worth breaking, if following them would prevent the app from being as functional/usable. A goal of this redesign is to make the app more functional, not less.
> > > 
> > > In particular, I want to reduce the number of clicks required for common actions (sorting) and move less common actions (editing filters) out of your way so you can focus on your tasks.
> > >
> > > ---
> > > *@mpcjanssen said:*
> > > 
> > > the quick filter from drawer selection will never go away as I use it a lot in the same way as you do :smile:
> >
> > 
> > *@Alphalpha007 said:*
> > 
> > Haha that's great Mark.
> > Guys, honestly I'd be so happy if the only changes brought in for now are lua enhancements, bug fixes, and a proper reminder system/Google calender enhancement. Otherwise, I've found that anything I need to do can be done with as few clicks as possible.
> > Sure, design improvements can help a lot in making it look more appealing, but I don't think the users of the app are a group who are very concerned about looks. I don't mean to sound offensive to anyone.
> 
> *@smichel17 said:*
> 
> I have no interest in change for the sake of change, either. The app works very well for me, too. There are, however, some pain points that I'd like to solve. But -- because the app does work very well, I will 
> not be content to solve those if the solution breaks the things that are already awesome about the app.
> 
> No offense taken, but based on my own preferences and #433, I am inclined to think that users do care about looks. Though I would agree that we put functionality and ease of use ahead of looks.
> 
> In short, you are a litmus test. If you don't look at my final proposal and think "Wow, this actually makes simpletask even easier to use", it's not my final proposal.

**Comment by smichel17** [comment]
Note to self: #433 has observations about Any.do's interface which are relevant to this issue.

**Comment by doranism** [comment]
@smichel17: do you still plan to work on the UI? It probably does not have the highest priority, because one year has past since your post. 

I found your iteration very promising and I agree that the goals are worthwhile. Therefor I thought about a way, how the main objections of @Alphalpha007 (focus on task list, reduce the amounts of clicks) and @mpcjanssen (keep quickfilter drawer) could be included. 

First of all: I think there is nothing to be said against a right side drawer:
in the Material design guidelines I found an example for a [Right nav on mobile](https://material.io/guidelines/layout/structure.html#structure-side-nav) (see animation).

So if the left drawer becomes the [main menu](https://material.io/guidelines/patterns/navigation-drawer.html#navigation-drawer-behavior), as the Guidelines propose, the right drawer could be used as quickfilter drawer. This way the task list can stay on the main screen in the focus of the users attention.

Since the functionality of the quickfilter drawer doubles up with parts of the view setup, I suggest to only keep the quickfilter drawer and enhance it:

- add prio to the quickfilter drawer to have all filter options in one place. If the three sections could be collapsed with [expansion panels](https://material.io/guidelines/components/expansion-panels.html#expansion-panels-usage) and the last state is remembered, the quickfilter drawer can be used as before but takes more functionality.
- add tabs to the drawer with "quickgroup/sort" and with "other" view options so that they can be changed as quickly as filters. (If its too tricky to have tabs in a drawer they could be opened by an action icon in the app bar as well.)

Scripting could be combined with the editor for the Lua-configuration in the overflow menu.

Maybe this can be some inspiration to simplify Simpletask and make it even faster :-)

**Comment by smichel17** [comment]
@doranism It is still on my list. I actually have a design iteration of this that I don't think exists outside my head. It is similar to what you suggest. 

Right now I'm focusing most of my attention on Red Moon. I want to get it feature-complete and polished, so I can move into bugfix-only mode. Once that happens, I'll come back to focusing on ST, it's just harder for me to split my time and attention between multiple projects at once.

**Comment by doranism** [comment]
@smichel17 Sure, it makes sense to concentrate on one project before starting another. 

Do you know the Material design [remixer](https://material.io/remixer/)? I didn't take a closer look yet, but maybe I can try some things out with that tool in a separate branch, if that would be any help. My coding "experience" is limited to some quickbasic coding 20 years ago and a few user script adaptions for Remember the Milk :-D Nevertheless I am open dive into new challenges.

**Comment by smichel17** [comment]
This is no longer on my list for the moment; I am not using SimpleTask enough to justify the time this would take. Since I doubt anyone else will come across to implement this, I'm going to close the issue. #1090 will get a large portion of the way there.
