### ISSUE TITLE
Time lag when selecting tasks in 8.0.6

### ISSUE THREAD

**Issue by Alphalpha007** [mpcjanssen/simpletask-android#491]
It takes 2 seconds for the blue color to fade in when clicking on a task on the main screen.

**Comment by mpcjanssen** [comment]
How big is your tasklist?

**Comment by Alphalpha007** [comment]
Just 24. Also, pressing back button doesn't clear the task selection. It exits the app.

**Comment by mpcjanssen** [comment]
Slowness will be fixed in next release. I will look into back behavior.

**Comment by mpcjanssen** [comment]
@Alphalpha007 when you press to close the selection, do you actually have to press it twice (once will remove the toolbar and once exits the app)?

**Comment by ddisanti** [comment]
I'm on Cloudless 8.0.6 from Play Store. I'm really please that now we can select task with a single tap. I don't noted the lag @Alphalpha007 mentioned. In my case, to de-select previously selected task, I've been using the "X", which is wrong (I know, is to undo Complete tasks) because pressing the BACK button the bottom menu disappear. Pressing the BACK bein again, SimpleTask exits.

**Comment by mpcjanssen** [comment]
@ddisant @Alphalpha007 both issues will be fixed in next release

**Comment by smichel17** [comment]
I believe the second part of this is/was a visual bug only. I can

- select a couple tasks 
- press back
  - bottom bar disappears but previously selected tasks remain blue
- select another, different task
  - Previously selected tasks stay blue in addition to the new one
- press edit
  - only the new task is edited

**Comment by Alphalpha007** [comment]
@smichel17 I second that.
