### ISSUE TITLE
Investigate splitting storage from main app as a dowloadable apk

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#513]
Probably using `android:sharedUserId`

**Comment by smichel17** [comment]
In Android M, or N, or something, isn't the permission model changing towards grant-as-requested rather than grant-on-installation?

If so, then we shouldn't split storage adaptors at all, they should just be shipped with the main app but disabled by default. That way...

- By default we require no permissions
- If the user enables automatic calendar reminders (which I think we should remove anyway, but that's another story), we request the calendar permission
- If the user enables dropbox, we request internet
- If the user enables cloudless, we request SD card

**Comment by mpcjanssen** [comment]
The issue with using one apk is that currently the cloudless version is guaranteed to not use the network. Wrapping it all together breaks this guarantee. For some people this matters a lot.

**Comment by mpcjanssen** [comment]
From gitter for archiving

> I would like to rebuild simpletask to be db only and have plugins for dropbox and local file storage sync. The DB should be leading
> see #513
> then all the multiple file 'nonsense' can be hidden in the file syncing adapters. For example sync a certain tag or list to a certain file
> hmm I like that

**Comment by mpcjanssen** [comment]
This is going to be a lot of work. With version 10 the backend interface is much simpler to implement and much more decoupled. So the only overhead left is the deploying of all flavours if there are changes to the main app.

Advantages are easier testing, easier to understand for the user. 

The small advantage of easier deployment is not worth the complexity in code and use.
