### ISSUE TITLE
Widget scrollbar changes size

### ISSUE THREAD

**Issue by Mirodin** [mpcjanssen/simpletask-android#514]
I am not sure if that is intended, but the scrollbar within the widget changes its length while scrolling. This is not a issue since the widget works fine but I think it is a bit weird since one can not estimate the list's length. 

Device: Alcatel One touch Idol 3
Android: 5.0.2
Widget size: 2x2

**Comment by Mirodin** [comment]
I forgot the version number... *shame*
It is 8.1.2

**Comment by smichel17** [comment]
It's been around for a while.

I believe it's that the scrollbar changes length depending on how many tasks are shown. Since some tasks are multi-line tasks, they take up more screen space but the scrollbar only counts them as one. Thus, the more multi-line tasks, the smaller the scrollbar.

 I'm not sure if it's intended.

**Comment by mpcjanssen** [comment]
It's not intended but I doubt it can be fixed. (Except maybe by chaning the view from a SrollListView

**Comment by mpcjanssen** [comment]
Nope RecyclerView has the same behavior (it's used in the main UI). Works as intended by Google, nothing I can do about it, sorry.

**Comment by mpcjanssen** [comment]
Update: one option to use would be`android:smoothScrollbar="false"` but that makes the scrollbar really jerky so I wont enable that.
