### ISSUE TITLE
selection in app effects add task from widget

### ISSUE THREAD

**Issue by leoauri** [mpcjanssen/simpletask-android#547]
It seems that if a task is selected in the app, the app in the background, and the add task shortcut in the widget is used, then the selected task is opened for editing rather than the new task dialog. Surely a new task would be intended behavior?

**Comment by smichel17** [comment]
I can confirm this bug.

**Comment by ddisanti** [comment]
Similar:
The same happens when sharing task:
1. Share a new task to SP.
 (at this point, when opening SP, this task shows as selected and it is possibly that the  task is off of the screen. You are aware that there is a selected task because Actionbar shows now the number of selected tasks)
2. Add a new task from "Add task" shortcut.
3. The task previously shared is open to edit it rather than an empty box.

It seems the problem has to do with the selection is not cleared.

**Comment by smichel17** [comment]
I'd call this two separate bugs.

1. The original bug
2. When editing a task that is shared to simpletask, that should be counted as an *add* task from the user's perspective, not a share task, and thus the item should not be selected when the user returns to simpletask.
