### ISSUE TITLE
"Create is threshold" setting is sometimes lost

### ISSUE THREAD

**Issue by djibux** [mpcjanssen/simpletask-android#644]
The "create is threshold" setting sometimes unchecks itself.

One way to reproduce this is to :
- Open filter an check "create is threshold"
- Move to the "script" tab and apply filter
- Open filter again, staying on the "script" tab and apply filter again (it's just a matter of opening and closing the screen, not making any change)
- Open the filter a third time: the "create is threshold" setting is unchecked in the "other" tab

**Comment by smichel17** [comment]
I cannot reproduce this. Two questions:

1. Can you try to reproduce by also changing another setting, to see if "create is threshold" is the only thing lost? 
2. Are you sure you didn't select a saved filter at some point in those steps?

I can "reproduce" this with the following steps:

- Select a saved filter X where create us threshold is not selected.
- Open the filter, check create is threshold, apply filter
- select filter X again
- Create is threshold is unselected again

I use "reproduce" in quotes because that's currently working as intended, though this is something I'd like to change. I thought there was an open issue about it but I can't seem to find it. Granted I'm on mobile.

**Comment by smichel17** [comment]
Never mind, found the bug by accident when I was looking at something else. Would have been tricky to find if I had not stumbled on it.

The way android handles memory management (simplified version) is that when a page or part of a page is no longer visible, it's kept around in memory for as long as it can be, for a faster restore if you ever return to that page. When the system needs more memory, it goes around and throws out stuff that's not visible. If that happens, the page gets loaded from scratch instead of from memory.

Why is that relevant to this bug? Because the `Create is threshold` checkbox was being set based on the `Hide create date` setting... but only when that tab is first created, not when it is restored from memory. So if you left the page and android *happened* to throw out that tab to make room in memory for a different app or different screen of simpletask, it'd be wrong only if it was different from hide create date, but correct otherwise.

I think. Here's the code, the bug is on the 4th line, it should be `INTENT_CREATE_AS_THRESHOLD`
```
public boolean getCreateAsThreshold() {
    Bundle arguments = getArguments();
    if (cbCreateAsThreshold == null) {
        return arguments.getBoolean(ActiveFilter.INTENT_HIDE_CREATE_DATE_FILTER, false);
    } else {
        return cbCreateAsThreshold.isChecked();
    }
}
```

**Comment by djibux** [comment]
That must be it!  Great job finding that one :)
