### ISSUE TITLE
No project checkboxes on selected item

### ISSUE THREAD

**Issue by Dynalt-glj1** [mpcjanssen/simpletask-android#690]
When I highlight an item and try to set a Project, there are no chrckboxes on the list. Opetstions appear to work correctly, but select status not visible. Galsxy S6

**Comment by mpcjanssen** [comment]
Could be a theming issue. Will look.

**Comment by mpcjanssen** [comment]
Issue occurs with light theme.

**Comment by mpcjanssen** [comment]
Issue doesn't occur on the add tasks screen where it works correctly.

**Comment by smichel17** [comment]
I can't reproduce. Could you include a screenshot so I know exactly what I'm trying to reproduce?

**Comment by mpcjanssen** [comment]
![screenshot_20161127-121224](https://cloud.githubusercontent.com/assets/146895/20647975/f657fcfa-b49a-11e6-82b4-5632ff45039d.png)

**Comment by smichel17** [comment]
Can't reproduce on my galaxy s4. I'll check if I can in an emulator, but I'm not hopeful.

**Comment by ddisanti** [comment]
I can't reproduce on my Galaxy Note 3 running Android 5.0.1.

**Comment by mpcjanssen** [comment]
I think this has to do with the Indeterminate checkbox theming.

**Comment by smichel17** [comment]
I vaguely recall making a change to indeterminate checkbox theming, in order to fix a different bug. I also recall indeterminate checkbox theming being all over the place and hard to understand, so it's entirely possible I messed it up at that time.

**Comment by barnoto** [comment]
I have the same experience only when using the "light" theme (checkboxes do not show when editing multiple tasks for contexts or projects).  Running on  CyanogenMod 13.1.2-ZNH2KAS3P0-bacon (Elderberry (5)) on OnePlus One.

**Comment by aurisnoctis** [comment]
This bug affects tags, too ( #698 ) @smichel17

**Comment by djibux** [comment]
I am also having the issue with the "light" theme.  Switching to another theme fixes the issue.
Like @barnoto I am using CyanogenMod.

**Comment by barnoto** [comment]
Hi Mark,
Thanks for the info.  Will you be issuing an update or is there a file to
download?
Thanks, Bruce

**Comment by barnoto** [comment]
Hi Mark,
It would be great if your donate app was renewable.  All it does is thank
me for a donation I made too long ago.

Thanks,
Bruce

**Comment by smichel17** [comment]
@barnoto There will be an update, just a few bugs are still being worked out I think. See the link below about  getting a debug version of the app (can be installed alongside the release) which has the changes and which you can use to help us test for bugs. 

https://gitter.im/mpcjanssen/simpletask-android?at=58a5a5ba0ad50ac315236840

**Comment by smichel17** [comment]
Also re: donations, you can give @mpcjanssen a gift directly via PayPal. The link is around somewhere, not sure off hand.

Also, I think this is the point where it's appropriate to mention snowdrift.coop. https://wiki.snowdrift.coop/about/intro (I'm part of our team of volunteers).

**Comment by mpcjanssen** [comment]
@barnoto PayPal link is in the help. @smichel17 pasted the link to the latest apk.

**Comment by barnoto** [comment]
Hi Mark,
I downloaded the app and debug version per the above link and have a new
problem (the checkbox problem per issue #690 is resolved, however.  Yay!)

Issue: Startup Simpletask.  You're in a filtered or unfiltered view,
whatever. Select an item, select edit.  The one item is there to edit. All
is good. Edit the item or cancel out, whatever, go back to the view of
items (a filtered view or not); De-select the previously selected item,
select a new item, select edit. The selected item PLUS the previously
selected item is there to edit. Go back, sure enough, you've only selected
the one item.  Now select a saved filter, select one item, select edit; the
previous two items show up for editing, but the item you just selected from
the new filtered view does not show up for editing. Okay, that's one
dimension of the problem.

If I had stayed in the first view and continued the cycle of selecting one
new item to edit, the list of items in edit view grows to include all the
recently selected items to edit plus the one new item you just selected.

I looked at your recent issues and since this isn't one of them, maybe this
is just something freaky about my phone or the way I installed the links
(app first, debug 2nd).  In the meantime I've uninstalled and re-installed
off of the Play Store and I'm in good shape (save for #690 which I
understand is fixed in your upcoming release).

I hope this isn't a waste of your time but I thought you might be
interested in the behavior I found.

Thanks for listening.

Bruce

**Comment by mpcjanssen** [comment]
@barnoto should be fixed in the beta versions on playstore. Opt-in for beta using https://play.google.com/apps/testing/nl.mpcjanssen.todotxtholo or https://play.google.com/apps/testing/nl.mpcjanssen.simpletask

If this is still an issue in the upcoming 9.0.0 please log a new issue.
