### ISSUE TITLE
The Todo.txt Format

### ISSUE THREAD

**Issue by martinlabuschin** [mpcjanssen/simpletask-android#746]
According to the [official todo.txt format rules](https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format#todotxt-format-rules), Simpletask is mixing up projects and contexts. 

- Projects are supposed to be declared by +
- And contexts are supposed to be declared by @

By following this rules, Simpletask could be combined with other todo.txt compatible apps like SwiftoDo/TodoTxtMac or jdotxt ...

**Comment by mpcjanssen** [comment]
Simpletask uses tags en lists because I find it more general and it makes use more flexible IMO. See https://github.com/mpcjanssen/simpletask-android/blob/master/app/src/main/assets/listsandtags.en.md for a rationale.


However there is a setting to use `todo.txt` terms Settings->Other->Use todo.txt terms which matches the defined todo.txt use.

**Comment by martinlabuschin** [comment]
Perfect, thanks!
