### ISSUE TITLE
Use app bar color as loading screen color

### ISSUE THREAD

**Issue by nvllsvm** [mpcjanssen/simpletask-android#749]
When using the black theme, the app loading screen appears as bright blue. This is jarring/blinding and out of place for a black theme.

This is also the behavior for the White and Dark themes so it sounds hard coded.

![screenshot_20170507-130350](https://cloud.githubusercontent.com/assets/6550543/25783200/02dca3a4-3326-11e7-98eb-e1fbeca06832.png)

I suggest using the color of the app bar as the loading screen color. That would ensure the White and Dark themes remain with the blue loading screen, but the black theme would have a dark grey loading screen.
![colors](https://cloud.githubusercontent.com/assets/6550543/25783268/685ae87a-3327-11e7-8da9-9a771c78d873.png)

**App:** Simpletask 9.0.2 from F-Droid
**Device:** OnePlus 3T
**Android:** 7.1.2
**ROM:** SultanXDA's LineageOS 14.1-20170430

**Comment by smichel17** [comment]
I did ST's current theming. Thanks for the feedback! I agree with you that it would be nicer to do this dynamically, but unfortunately it's not possible on Android (loadscreen styling is declared in the manifest, at compile time).

It used to be white, since white is the background color for the app by default. Blue was a compromise between that and changing to a black/gray load screen, since it's slightly darker and there is some blue in all of the themes (app bar in both the light and dark theme; FAB in the black theme). 

I think we can do slightly better, by adding an animation (description in #518), but that's a polish thing, and I think it's more important to get core functionality locked down and finished before we do too much polish.

**Comment by mpcjanssen** [comment]
I actually would prefer for this to be black (as it used to be). But I agree it will always look off somehow.

**Comment by smichel17** [comment]
It used to be white. I think there's an argument for black as the default as it's more "blank" and won't flash bright at night. Not convinced whether black or current blue + animation would be better.

**Comment by mpcjanssen** [comment]
Changed the background to black. This looks less jarring to my eyes. There is no way to properly fix this until Android fixes the theme loading order.
