### ISSUE TITLE
Unsaved task is saved when pressing back button

### ISSUE THREAD

**Issue by nvllsvm** [mpcjanssen/simpletask-android#751]
Pressing the back button while in the process of creating a new task will result in the task being saved. Given that there is a save button, I expect the back button to cancel and not save whatever tasks have been entered.

**App:** Simpletask 9.0.2 from F-Droid
**Device:** OnePlus 3T
**Android:** 7.1.2
**ROM:** SultanXDA's LineageOS 14.1-20170430

**Comment by smichel17** [comment]
Thanks for the feedback! This is actually intentional: if you accidentally save a task with the back button, it's easy enough to delete it later, but if you accidentally discard it, there's no way to recover.

While it is annoying to create tasks by accident (I do it too!), for now it's the lesser of two evils. We used to have a setting to choose between the two behaviors, but ST already has too many settings and I'm loath to reintroduce this one.

Eventually I'd like to add/edit all tasks from the Main screen, and only use the separate Add Task screen for the `Edit shared tasks` feature or when adding from an external screen; this would remove the need for a setting altogether (back button can hide the entry text box, but we can keep whatever text was in it and restore that text when the box is opened again). 

> Given that there is a save button

There's a discard button (`X` in the upper left), too!

**Comment by nvllsvm** [comment]
Makes sense.

Having a popup to add tasks from the main screen with an auto-restore of text would resolve this.
