### ISSUE TITLE
Willing to change the +background prefill

### ISSUE THREAD

**Issue by Candidesk8** [mpcjanssen/simpletask-android#773]
Hello,

I'm looking for a way to change pre-filled text giving sample of formatting new task.
Instead of +background, I would rather have a correct formatting sample.
I looked but didn't found where this was coded,  although i'm not a coder, just a user.

Any help would be very welcome!

#### General information
* Device : *FairPhone FP1U*
* OS : *Android 4.2.2*
* Source : *f DROID*
* Version : *v9.0.7*

**Comment by mpcjanssen** [comment]
The +background is set in the settings and read from the Config object. Can you give an example of what you would like it to be?

**Comment by Candidesk8** [comment]
It would be something like this :
(Priority_level_letter) yyyy-mm-dd text including @list and +tag in any order with other @lists or +tags with also a due:yyyy-mm-dd t:2017-08-31 

Le 27 août 2017 22:59:56 UTC+02:00, Mark Janssen <notifications@github.com> a écrit :
>The +background is set in the settings and read from the Config object.
>Can you give an example of what you would like it to be?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mpcjanssen/simpletask-android/issues/773#issuecomment-325224395

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by smichel17** [comment]
@Candidesk8 I'm not sure what "It" refers to. Could you format it like:

Steps:

- do this
- then this
- finally, this

Actual result: Something
Expected result: Something else

**Comment by mpcjanssen** [comment]
@Candidesk8 do you mean the text that is shown when there is no text in the add task field? Please give details as @smichel17 said (possibly with screenshots)

**Comment by Candidesk8** [comment]
Yes, I want to be able to change the text " that is shown when there is no text in the add task field"

Do this really need screenshot?

Le 5 septembre 2017 13:22:19 UTC+02:00, Mark Janssen <notifications@github.com> a écrit :
>@Candidesk8 do you mean the text that is shown when there is no text in
>the add task field? Please give details as @smichel17 said (possibly
>with screenshots)
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mpcjanssen/simpletask-android/issues/773#issuecomment-327147112

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by smichel17** [comment]
@Candidesk8 Normally when there is no text in the add task field, it *does* show a hint as you would like. You can enable/disable this from the `Show hints` checkbox in the 3 dot menu on the add task screen.

<img alt="hint" height="300" src="https://user-images.githubusercontent.com/6563664/30072905-d699c70e-9239-11e7-8be6-fb1bd53b3125.png">

There is a separate feature for appending some custom text when adding from the background (sharing to simpletask, instead of hitting the + button in the app). By default, that text is `+background`, but you can customize it in the `Features` section of the settings.

<img alt="background setting" height="600" src="https://user-images.githubusercontent.com/6563664/30073177-e328f520-923a-11e7-9de3-9faea3f6bf1c.png">

This is why it is hard to tell exactly what the problem is. Providing the steps you took before the issue happened, and/or a screenshot (optional) is very helpful to clear up confusion.

---

However, I now have a *guess* what steps you took. *If* I'm right about my guess, you can solve your problem by going to `Settings` > `Features` and changing the `Background text` setting to blank (tap on it, delete `+background`, and press ok).

**Comment by mpcjanssen** [comment]
The example text is defined in strings.xml.

**Comment by Candidesk8** [comment]
Thanks a lot @smichel17 for the imaged answer! As one said, a picture is worth thousand words ;-)

But what I wish it to have the opportunity, as a user, to set an alternate background text, something looking more or less like this, from previous post:
> Priority_level_letter) yyyy-mm-dd text including @list and +tag in any order with other @lists or +tags with also a due:yyyy-mm-dd t:2017-08-31

It would be named +alternate-background or +theme

If I have to change this in the strings.xml, I guess I'll have to compile my version of the software, right?

Anyway, big big _thank you_ for your time, your explanations and your reactiveness <3 !!!

Le 5 septembre 2017 20:38:50 UTC+02:00, Mark Janssen <notifications@github.com> a écrit :
>The example text is defined in strings.xml.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mpcjanssen/simpletask-android/issues/773#issuecomment-327265341

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by mpcjanssen** [comment]
@Candidesk8 you are correct. You will need to compile your own version to change this text. I don't really see the point in adding (and maintaining) a setting for this, there are already too many settings.
