### ISSUE TITLE
[feature request] what have i done yesterday

### ISSUE THREAD

**Issue by symbolisch1234** [mpcjanssen/simpletask-android#779]
I would love to have an option (!) for simpletask to create "done" files. that is every day it creates a file named done-YYYY-MM-DD.txt which simply includes all the tasks that were completed on that day.

i know there is the history, and i am thankful for that, but this would make accounting when you did what easier.

thanks in advance.

**Comment by smichel17** [comment]
You may find my saved filters and lua scripts useful: [saved_filters.txt](https://github.com/mpcjanssen/simpletask-android/files/1308672/saved_filters.txt), [config.lua.txt](https://github.com/mpcjanssen/simpletask-android/files/1308674/config.lua.txt)

To import them into ST:

- Download the files
- Remove the `.txt` ending from the config (I only added it because github wouldn't allow me to upload a file with a `.lua` extension)
- Copy them to the same folder as the todo.txt file on your phone (or dropbox)
- Open ST, open the right drawer, tap the up/down arrows menu item, then choose `import`
    - This will add my filters in addition to your filters -- nothing will be lost.
- Close the drawer, and select `Lua Config` from the overflow (3 dot) menu.
- From the lua config screen, tap the up/down arrows menu item, then select `Import`
    - If you have any of your own lua config, now is the time to save (copy) it
    - Hit the X in the upper right corner to finish the import -- **your previous lua config will be lost**

**Comment by mpcjanssen** [comment]
Best way for this would be to add a Lua callback which determines the done filename based on the todo file name and date.

**Comment by mpcjanssen** [comment]
Also note that completed tasks already include the completion date. So if you archive, it's easy to use a script to analyze done.txt for tasks completed yesterday. 
Also to ensure only the tasks completed today means that if you don't archive at midnight simpletask somehow needs to put yesterdays completed tasks in yesterdays `done.txt` if you archive today. Because of these kinds of scenarios, I will not add this.

As a result this functionality
