### ISSUE TITLE
question: Task text limited to one paragraph only?

### ISSUE THREAD

**Issue by karel201712** [mpcjanssen/simpletask-android#837]
Hi and thanks for reading my post.

I've only just discovered Simpletask and I am quite overwhelmed. But before I get too excited, there is one issue that may prevent me from using it as a replacement for my current 2do app and it is this:

the task text appears to be limited to one paragraph. Whenever I add more paragraphs into the text, the app creates one task for each paragraph.

I know I need to have multiple paragraphs in the body/comment of my task. Is that somehow possible with Simpletask, pls?

Many thanks in advance!
Best regards,
Karel

**Comment by smichel17** [comment]
This is not possible, and I don't see it happening, well, ever. Simpletask stores tasks in the todo.txt format, which specifies one line per task.

There is a variant hanging around somewhere that uses taskwarrior as a backend instead of todo.txt, which might (?) support multi-line task bodies, but I'm not sure if @mpcjanssen is actively maintaining it, and I don't think you'd be able to add multi-line tasks or edit their text from within Simpletask, anyway (due to how the add/edit screen is currently implemented).

**Comment by karel201712** [comment]
Thank you for your reply. I was worried it might be something like that. I must say, I went thru possibly a hundred task related apps in the past year and Simpletask might be the only one that combines UI simplicity and huge organizing potential thanks to the way it filters tasks with tags.
Best regards,
K

**Comment by smichel17** [comment]
Simpletask is flexible enough that you can *almost* do it. Here's the two best workaround I can think of: 

1. Write your notes on physical paper and take photos (or use a tool like [this](https://play.google.com/store/apps/details?id=nl.mpcjanssen.uc), then share the image to simpletask. It'll show up as a URI beginning with `content://` and you can open it with a long press. Obvious downside being you can't edit it unless you know of a really good image editor. Might still be good for notes. Also, right now ST doesn't support linking files (it adds the content as tasks instead) but that's a feasible enhancement, and then you could edit with a different app. 
2. Use `@lists` to represent tasks. With 'Pre-fill' enabled on the add task screen, you'll only have to enter the `@task_name` for the first line of the task. Downside: if you wanted to change the metadata of the task, you'd have to it for all paragraphs; that isn't *too* hard, since you can select multiple tasks, but might get tiresome after a while. Lua scripts might be able to help with that, a little. 

I'll also note: I've never felt the need to enter multi-paragraph tasks. The todo.txt format was inspired by / designed for GTD, and tasks are the rough equivalent of next-actions. Anything large enough to warrant multiple paragraphs seems more like a project to me, so I'd be inclined to split it up into bite-sized tasks (ie, next-actions) anyway; I do have projects-as-a-single-task in my todo file, but they're not ones I'm actively working on; if/when I do get around to them, my first step would be to figure out what the next-actions for that project *are*, and move to tracking it similarly to alternative 2 above. So, that's a different way of thinking about it.

> Simpletask might be the only one that combines UI simplicity and huge organizing potential thanks to the way it filters tasks with tags.

I agree; ST is the best todo app I've come across, on mobile or desktop, and has slowly become the only todo app I use. I can share more about my workflow in a week or so if you're interested but I don't really have any more time to respond right now as it's finals week and I'm now awake enough to start work :P

**Comment by karel201712** [comment]
Thank you again for your kind reply. Very interesting information. I will try your advices and see if something works for me. As for the multiple paragraphs, I just know for sure I need them. It's just the way I use these apps. Body of my tasks sometimes contains detailed information that I don't have to store anywhere else.
I am too very busy at the moment and I am certainly in no hurry to finish my hunt for my new 2do app as it's been going on for a while already.
Best regards,
Karel

**Comment by mpcjanssen** [comment]
The taskwarrior backend supports annotations which could support this usecase fairly well. The UI of simpletask itself is not able to handle these annotations elegantly yet though.

**Comment by mpcjanssen** [comment]
`todo.txt` doesn't support multiline tasks and implementing it will stray to far away from the standard. Not going to happen in Simpletask. You could keep an eye https://github.com/mpcjanssen/simpletask-taskwarrior which might include it because the backend supports it.
