### ISSUE TITLE
Prefill is not working

### ISSUE THREAD

**Issue by memeplex** [mpcjanssen/simpletask-android#890]
Just that, the box in the menu is checked of course, but pressing enter leaves me in an empty new line. Also pressing enter in the middle of a task splits it into two lines, but I have read somewhere that it should add a new task.

**Comment by smichel17** [comment]
I can reproduce this and know the which part of the code is related.

Workaround for now: if you put your device in landscape mode, the on-screen "next" button will have the proper behavior.

**Comment by smichel17** [comment]
This is absurd. I assumed the problem was caused by the recent changes I made to this part of the code. To verify this, I went back and ran a version of the app from before I made any changes.

I confirmed that my changes did, in face, break some things (the previous behavior worked again with the Samsung keyboard). However,

- The behavior was not the exact same as previously -- it still displays the 'Return' symbol on the keyboard instead of "Next".
- For the swipe keyboard, it does not work *even though it did work previously*.
    - Even crazier, *with the swipe keyboard, the callback added with `setOnEditorActionListener` (AddTask line 123 on commit b0cc5980) doesn't even get called.*

I'm at an airport right now and need to head to my flight soon. I'll come back to this in a bit.

**Comment by bushrang3r** [comment]
Any progress on this issue?

**Comment by mpcjanssen** [comment]
It is very hard to make this work without breaking enter in other scenarios (like splitting up tasks) and working on all types of keyboard. I think the best way forward is actually to add a separate button to add a new prefilled line.

**Comment by smichel17** [comment]
I agree. Also, then it will be possible to break a task into two lines using enter, which I actually do want to do occasionally

**Comment by mpcjanssen** [comment]
Overloading the enter keyboard key to act as a new task with prefill key was not working reliably and also not always intuitive. For now the prefill is a separate button on the toolbar. It's very unlikely it will ever return to a keyboard key so this issue is not relevant anymore.
