### ISSUE TITLE
What about time tracking?

### ISSUE THREAD

**Issue by geniusupgrader** [mpcjanssen/simpletask-android#896]
I would like to track the time on each task / project. Something like punching in and out the with a button or similar. I know there are (open source) time tracker on android (most notably [ATimeTracker](https://github.com/netmackan/ATimeTracker) and maybe [kimai](https://www.kimai.org/)), but none of them uses a plain text approach like todo.txt. 

**So my question:**
Is this in the scope of simpletask? Or should there be an other tool/program, which reads in the todo.txt file, extracts the task names/projects and tracks the time in its own format?

How do you track time on your tasks?

Greets

**Comment by mpcjanssen** [comment]
I don't track my time on a task level so I don't have any useful tips. I can say that task timing  is definitely out of scope for simpletask.

I have seen people use https://play.google.com/store/apps/details?id=net.phlam.android.clockworktomato which apparently can add timing information to todo.txt files so that might be worth checking out.

**Comment by geniusupgrader** [comment]
thanks for this recommendation @mpcjanssen,

but unfortunately clockworktomato is not open source, or is it?
It would be nice to have an open source project, which also works with todo.txt together.
Because there is nothing on the market at the moment, I'm tinkering with the thought to program my own open source android app to nourish my programming skills.
