### ISSUE TITLE
Write/Sync with or pick up/merge local todo file with dropbox file

### ISSUE THREAD

**Issue by timoc** [mpcjanssen/simpletask-android#923]
I would like to be able to edit a local version of the todo.txt file used by simpletask dropbox. This is so that i can make sync'ed todo.txt changes with from desktop that does not have dropbox on it. These changes would be with vim, emacs, todo-cli or whatever with the todo.txt over ssh (via gnuroot/termux etc) the phone.

The assumption here is that simpletask would sync the local todo.txt and done file changes to/with dropbox.

**Comment by timoc** [comment]
The use case is this:
I am performing a weekly review at a desktop, but that desktop does not have dropbox installed- and i cannot access dropbox file via the web interface (corporate policy forbids). I want to cut'n'paste or quickly put a next action into my todo.txt for simpletask on my phone to be able to sync.  

I can edit files remotely on my phone (via ssh) from the desktop. So thinking in todo.txt as a shared file terms, i was looking for local phone access to it. I've come up with cut'n'paste workaround using evernote.

Evernote sync would be cool, or google tasks.

**Comment by smichel17** [comment]
It seems like the way to do it would be to use ST cloudless and then a separate app for syncing the todo.txt file to dropbox (or your service of choice). That's what I've been doing with nextcloud (since before the nextcloud variant existed, and I just haven't switched yet). It works pretty well.

I've described my setup more precisely elsewhere in the issues here, not sure exactly where off hand (and hard to find since I'm on mobile).
