### ISSUE TITLE
Make widget refresh when new day starts to account for threshold dates

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#93]
From http://mpcjanssen.nl/tracker/issues/63

Correct me if I'm wrong, but if there are threshold dates and tasks become active on a new day, the widget doesn't seem to realize that...

mpcjanssen added on 2014-01-27 22:03:29:
You're not wrong. This is a scenario I didn't consider :-}

The application itself will also not refresh correctly after midnight, but because that gets redrawn when you reopen the app it's less of an issue. This is a bug.

**Comment by isavcic** [comment]
@mpcjanssen this also occurs on Lua filter.

For example:

```
if due~=nil then
    return os.time() > due and os.time() - 86400 < due
end
return false;
```

I use the above filter to show only due:today tasks.

Since the todo.txt doesn't change, widget doesn't change and doesn't reflect new due: tasks when the day passes.

Clicking on the widget shows filtered tasks correctly. Modifying todo.txt in any way refreshes the widget.
