### ISSUE TITLE
manual archiving fails, saying "No tasks to archive." (cloudless 10.2.9 f-droid)

### ISSUE THREAD

**Issue by scheunengeist** [mpcjanssen/simpletask-android#955]
Hey, once again: sweet app!

Currently having problems archiving done tasks. Selecting 'archive' from the menu results in a message telling me there are "No tasks to archive." Manually double-checking the todo.txt file reveals this to be not true, as expected. I'm using version 10.2.9 from F-Droid, and I am not using auto-archive.

Tried so far: force-closing/restarting the app; rebooting phone; manually selecting todo.txt file

Can anybody confirm this, or is it just me missing something?
Thanks!

**Comment by smichel17** [comment]
I vaguely recall talking about a change a while back so that only visible tasks would be archived. Don't remember if we ended up doing that or not.

**Comment by scheunengeist** [comment]
Ah, apparently you did. I was just able to archive 400+ tasks after making done tasks visible. So, thanks for the hint. :)
Somehow weird behaviour, though. What's the rationale? Is the discussion you mentioned still accessible somewhere?

**Comment by smichel17** [comment]
I know it's accessible because it would either have been in this repo or in one of the chat rooms, which have public history (matrix and gitter do, anyway). Finding it, on the other hand..

I didn't see anything in a quick search of the issues. Maybe you could search the commit logs and see if the commit message mentions any issues or gives a reason?

**Comment by smichel17** [comment]
Yep, that was a good approach. Discussion in #131

**Comment by scheunengeist** [comment]
Thanks for digging it up. True, it's a rather short discussion. Didn't quite get *why* it makes more sense. :)
Anyway, no big deal, now that I know. If that's the desired and intended behaviour, I'll adjust my workflow a tad and that's that.
Cheers!

**Comment by smichel17** [comment]
If I were to hazard a guess, I'd say the reason is likely to support a workflow someone wants different lists and tags to be more independent of one another (eg, as multiple lists rather than contexts in a master list); the current behavior lets you easily archive all the completed tasks in just one list.

Personally I guess I don't archive that much :P. I do have an `All` filter that shows everything, though.

**Comment by scheunengeist** [comment]
Hm, yes, if someone wanted to archive the done tasks of one set of tasks (say, @work) while keeping other done tasks in the todo.txt file, then this behaviour would be helpful. Although off the top of my head, I can't come up with a scenario where this would really be useful. I'm sure there is one, though.

As for discussion and default settings, I guess it's really up to @mpcjanssen 's vision where this project should go. ST is already a mighty implementation and extension of the original todo.txt procedure, and hands down the most flexible todo list I've used in a long time.
I'll just be content knowing what each button does for the time being. :)
But thanks for putting thought in this minor issue of mine.
