### ISSUE TITLE
Drag and drop sorting feature request - one more try ;)

### ISSUE THREAD

**Issue by Kamul-PL** [mpcjanssen/simpletask-android#989]
I know that this case appeared here many times. But I wanted to ask again to consider adding a drag'n'drop tasks sorting option. I don't think about any miracles here. It would be enough to change the position of one task relative to another within one single list/tag range. There's no necessity to extend the todo.txt format. Let the sorting be based solely on changing the position of task in the text file. It would be enough than to sort tasks by occurrence in the todo.txt file.

Currently it's needed to read each item with a given priority from current list. It's cumbersome and creates a risk of missing a task, when the list gets long. Adding d'n'd sort possibility will significantly increase the comfort of use (not just for me, I believe), because it will allow you to conveniently prioritize tasks by changing their position in the list.

I would like to ask you to reconsider this feature request.  I know that if I don't like Simpletask, I can change to something else at any time. The problem is that I've tried that a few times, but with no success.;) Simpletask is simply the best: it's lightweight, simple, works on regular text files and saves files in shared memory, which is also important to me. So far, I haven't found anything close to Simpletask.

**Comment by smichel17** [comment]
For what it's worth, I don't have anything against drag-and-drop sorting and I don't think @mpcjanssen does, either.

The problem is that it's very challenging to implement, both from a technical *and a UX* perspective. It has been proposed and discussed quite a bit before in #39, #406, #636, and #748. As far as I know, we never ended up with a complete design for how it would work. Given that it is *also* a lot of work to build, it's unlikely that will ever happen without finishing the design first. We would want:

- **Specs for how the tasks in the todo.txt file should be changed when a task is dragged.** One tenet of ST's design is that there's no extra state that's not stored in the todo.txt file (this is one of the things that makes it great, as you mention!). If it's just in file order, it's pretty clear what should happen, but with other sorts, things get complex quickly.
- **How the UI/UX should be changed to support drag and drop.** Right now both tap and long press have actions associated with them, so drag-and-drop will need to either be added some other way, or some of the existing functionality needs to be shuffled around to make room for drag-and-drop.
- **A simpler to implement, proof of concept version.** Since this is also a hard thing to implement technically, we'd want to build something with a more reasonable scope, first. For example, maybe drag and drop is only supported when sorting in file order, or maybe it's only possible to drag between groups, not ordering within a group.

That would *by no means* guarantee that drag-and-drop ends up being implemented, but it would take the chances from "basically nothing" to "possible".

**Comment by mpcjanssen** [comment]
Opening extra issues wont make it more likely to happen. @smichel17 gave a good summary. Due to complexity and unclear behaviour in sorts besides file order not going to happen anytime soon. Please continue discussion at #748. PRs also welcome.
